{{ if .Values.codimd.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "codimd.name" . }}
  labels:
  {{- include "codimd.labels" . | nindent 4}}
  {{ if .Values.codimd.serviceAccount.annotations }}
  annotations: {{ .Values.codimd.serviceAccount.annotations | toYaml | nindent 4 }}
  {{ end }}
{{ end }}
